Update HTMLCHECK.yml

diff --git a/.github/workflows/HTMLCHECK.yml b/.github/workflows/HTMLCHECK.yml
--- a/.github/workflows/HTMLCHECK.yml
+++ b/.github/workflows/HTMLCHECK.yml
@@ -18,15 +18,30 @@ jobs:
   HTMLCHECK:
     runs-on: ubuntu-latest
     steps:
-    - run: lsb_release -a
-    - run: uname -a
+    # - run: sudo apt update && sudo apt upgrade -y
+    # - run: sudo sed -i 's/focal/devel/g' /etc/apt/sources.list
+    # - run: sudo apt update && sudo apt upgrade -y
+    # - run: sudo apt --with-new-pkgs upgrade -y
+    # - run: sudo apt autoremove && sudo apt autoclean
+    # - run: lsb_release -a
+    # - run: uname -a
     - uses: actions/checkout@v3
+    - run: |
+        ls -la
+        git -C . rev-parse
+        echo $?
+        if ! git -C . rev-parse 2>/dev/null; then
+          echo "Git check fails"
+        fi
     - name: HTML5Validator
-      uses: Cyb3r-Jak3/html5validator-action@master
+      uses: Cyb3r-Jak3/html5validator-action@v7.1.0
       with:
-          root: pages/
+          root: ./
           log_level: INFO
           css: true
+          skip_git_check: true
+      env:
+        HTML5_ACTION_DEBUG: true
     - uses: actions/upload-artifact@v3
       with:
           name: log
